name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make bonus

  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
